services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql # Bind mount for persistent data

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:8080" # HostPort:ContainerPort for HTTP
      - "5001:8081" # HostPort:ContainerPort for HTTPS (if needed)
    volumes:
      - ./backend:/app # Mount the local code into the container
    command: dotnet watch run # Ensure live reloading
    depends_on:
      - mysql

  frontend:
    build:
       context: ./frontend # Adjust the context to your frontend directory
       dockerfile: Dockerfile
    ports:
       - "3000:8080" # Expose the frontend port on the host
    volumes:
        - ./frontend:/app # Mount the local code into the container
        - /app/node_modules # Prevent overwriting node_modules
    environment:
        REACT_APP_API_URL: "http://localhost:5000/api"
    depends_on:
     - backend