services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:8080" # HostPort:ContainerPort for HTTP
      - "5001:8081" # HostPort:ContainerPort for HTTPS (if needed)

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql # Bind mount for persistent data